In [34]:
import pandas as pd

In [35]:
file_path = 'C:/users/thdwo/busan_jupyter/04_교통데이터분석/01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard (0)/trfcard.csv'

df_bus_card_org = pd.read_csv(file_path)
df_bus_card_org

,on_date,off_date,route_name,descr,age_type,trans_yn,addfee_yn,start_bstop,start_gps_x,start_gps_y,end_bstop,end_gps_x,end_gps_y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
1,20200327051514,20200327054956,175,문덕-고속터미널-선린병원-달전,일반,N,N,준양주택3차,129.403063,35.960871,오거리,129.366312,36.031816
2,20200327052343,20200327054659,200,양덕-남구청(야구장)-구룡포,일반,N,N,두호동주민센터,129.378910,36.060370,남구보건소,129.396855,35.992624
3,20200327052449,20200327055412,100,문덕-흥해-신광,일반,N,N,천마아파트,129.409928,35.949403,홈플러스,129.364640,36.030950
4,20200327052848,20200327055231,175,문덕-고속터미널-선린병원-달전,일반,N,N,오천농협세계지점,129.415970,35.967450,죽도시장,129.365169,36.035704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978,20200327232513,20200327232800,101,양덕-고속터미널-동해,일반,Y,N,포은중앙도서관,129.367873,36.043187,롯데아파트,129.377403,36.056943
4979,20200327232740,20200327233319,107,문덕-시외(고속)터미널-흥해,일반,N,N,KTX포항역(시내행),129.342368,36.072374,우현경로당,129.362232,36.049878
4980,20200327232829,20200327233446,500,문덕-시외터미널-흥해-청하-월포,일반,N,N,시외버스터미널,129.350290,36.013280,연일파출소,129.345750,35.997470
4981,20200327233328,20200327233442,107,문덕-시외(고속)터미널-흥해,일반,N,N,우현경로당,129.362232,36.049878,도심환승센터,129.365165,36.043435
4982,20200327233622,20200327234014,105,양덕-시외터미널-지곡,일반,N,N,포은중앙도서관,129.367873,36.043187,두호남부초등학교,129.373390,36.060530

#### - 데이터 형태 및 결측치 확인하기

In [36]:
df_bus_card_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4983 entries, 0 to 4982
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   on_date      4983 non-null   int64
 1   off_date     4983 non-null   int64
 2   route_name   4983 non-null   object
 3   descr        4983 non-null   object
 4   age_type     4983 non-null   object
 5   trans_yn     4983 non-null   object
 6   addfee_yn    4983 non-null   object
 7   start_bstop  4983 non-null   object
 8   start_gps_x  4983 non-null   float64
 9   start_gps_y  4983 non-null   float64
 10  end_bstop    4983 non-null   object
 11  end_gps_x    4983 non-null   float64
 12  end_gps_y    4983 non-null   float64
dtypes: float64(4), int64(2), object(7)
memory usage: 506.2+ KB

## 1. 컬럼명을 한글명으로 변경
#### - 1. 영문명과 한글명이 있는 메타 정의서 찾기
#### - 2. Dictionary로 가져오기
#### - 3. rename()을 사용하여 바꾸기

In [37]:
df_bus_card_col_org = pd.read_excel('./01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard (0)/trfcard_columns.xlsx', \
                               sheet_name = '컬럼 정의서', \
                               usecols = 'B : C',
                               header = 2)

df_bus_card_col_org

       컬럼명 (영문)     컬럼명 (한글)
0       on_date         승차시각
1      off_date         하차시각
2    route_name          노선명
3         descr         노선설명
4      age_type         승객연령
5      trans_yn         환승여부
6     addfee_yn       추가운임여부
7   start_bstop        승차정류장
8   start_gps_x  승차정류장 GPS X
9   start_gps_y  승차정류장 GPS Y
10    end_bstop        하차정류장
11    end_gps_x  하차정류장 GPS X
12    end_gps_y  하차정류장 GPS Y

#### - list 형태로 추출
#### - to_dict('records'): 각 행들을 Dictionary로 전환해서 추출

In [38]:
df_bus_card_col_org_dict = df_bus_card_col_org.to_dict('records')

df_bus_card_col_org_dict

[{'컬럼명 (영문)': 'on_date', '컬럼명 (한글)': '승차시각'},
 {'컬럼명 (영문)': 'off_date', '컬럼명 (한글)': '하차시각'},
 {'컬럼명 (영문)': 'route_name', '컬럼명 (한글)': '노선명'},
 {'컬럼명 (영문)': 'descr', '컬럼명 (한글)': '노선설명'},
 {'컬럼명 (영문)': 'age_type', '컬럼명 (한글)': '승객연령'},
 {'컬럼명 (영문)': 'trans_yn', '컬럼명 (한글)': '환승여부'},
 {'컬럼명 (영문)': 'addfee_yn', '컬럼명 (한글)': '추가운임여부'},
 {'컬럼명 (영문)': 'start_bstop', '컬럼명 (한글)': '승차정류장'},
 {'컬럼명 (영문)': 'start_gps_x', '컬럼명 (한글)': '승차정류장 GPS X'},
 {'컬럼명 (영문)': 'start_gps_y', '컬럼명 (한글)': '승차정류장 GPS Y'},
 {'컬럼명 (영문)': 'end_bstop', '컬럼명 (한글)': '하차정류장'},
 {'컬럼명 (영문)': 'end_gps_x', '컬럼명 (한글)': '하차정류장 GPS X'},
 {'컬럼명 (영문)': 'end_gps_y', '컬럼명 (한글)': '하차정류장 GPS Y'}]

#### - Dictionary에 데이터 추가하기: dict['key'] = 'value'

In [39]:
df_bus_card_col_new_dict = {}

for i in range(0, len(df_bus_card_col_org_dict)) :
    df_bus_card_col_new_dict[df_bus_card_col_org_dict[i]['컬럼명 (영문)']] = df_bus_card_col_org_dict[i]['컬럼명 (한글)']
    
df_bus_card_col_new_dict

{'on_date': '승차시각',
 'off_date': '하차시각',
 'route_name': '노선명',
 'descr': '노선설명',
 'age_type': '승객연령',
 'trans_yn': '환승여부',
 'addfee_yn': '추가운임여부',
 'start_bstop': '승차정류장',
 'start_gps_x': '승차정류장 GPS X',
 'start_gps_y': '승차정류장 GPS Y',
 'end_bstop': '하차정류장',
 'end_gps_x': '하차정류장 GPS X',
 'end_gps_y': '하차정류장 GPS Y'}

In [40]:
df_bus_card_kor = df_bus_card_org.rename(columns = df_bus_card_col_new_dict)

df_bus_card_kor

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
1,20200327051514,20200327054956,175,문덕-고속터미널-선린병원-달전,일반,N,N,준양주택3차,129.403063,35.960871,오거리,129.366312,36.031816
2,20200327052343,20200327054659,200,양덕-남구청(야구장)-구룡포,일반,N,N,두호동주민센터,129.378910,36.060370,남구보건소,129.396855,35.992624
3,20200327052449,20200327055412,100,문덕-흥해-신광,일반,N,N,천마아파트,129.409928,35.949403,홈플러스,129.364640,36.030950
4,20200327052848,20200327055231,175,문덕-고속터미널-선린병원-달전,일반,N,N,오천농협세계지점,129.415970,35.967450,죽도시장,129.365169,36.035704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978,20200327232513,20200327232800,101,양덕-고속터미널-동해,일반,Y,N,포은중앙도서관,129.367873,36.043187,롯데아파트,129.377403,36.056943
4979,20200327232740,20200327233319,107,문덕-시외(고속)터미널-흥해,일반,N,N,KTX포항역(시내행),129.342368,36.072374,우현경로당,129.362232,36.049878
4980,20200327232829,20200327233446,500,문덕-시외터미널-흥해-청하-월포,일반,N,N,시외버스터미널,129.350290,36.013280,연일파출소,129.345750,35.997470
4981,20200327233328,20200327233442,107,문덕-시외(고속)터미널-흥해,일반,N,N,우현경로당,129.362232,36.049878,도심환승센터,129.365165,36.043435
4982,20200327233622,20200327234014,105,양덕-시외터미널-지곡,일반,N,N,포은중앙도서관,129.367873,36.043187,두호남부초등학교,129.373390,36.060530

## 2. 분석요소 주제 정하기, 추출하기

### 2.1 기준월 및 기준일자별 버스 이용량 분석 비교

In [41]:
df_bus_card_kor = df_bus_card_kor.astype({'승차시각' : 'str'})
df_bus_card_kor = df_bus_card_kor.astype({'하차시각' : 'str'})

df_bus_card_kor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4983 entries, 0 to 4982
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   승차시각         4983 non-null   object
 1   하차시각         4983 non-null   object
 2   노선명          4983 non-null   object
 3   노선설명         4983 non-null   object
 4   승객연령         4983 non-null   object
 5   환승여부         4983 non-null   object
 6   추가운임여부       4983 non-null   object
 7   승차정류장        4983 non-null   object
 8   승차정류장 GPS X  4983 non-null   float64
 9   승차정류장 GPS Y  4983 non-null   float64
 10  하차정류장        4983 non-null   object
 11  하차정류장 GPS X  4983 non-null   float64
 12  하차정류장 GPS Y  4983 non-null   float64
dtypes: float64(4), object(9)
memory usage: 506.2+ KB

In [42]:
df_bus_card = pd.DataFrame()

df_bus_card['승차시각'] = pd.to_datetime(df_bus_card_kor['승차시각'])
df_bus_card['하차시각'] = pd.to_datetime(df_bus_card_kor['하차시각'])
df_bus_card['승객구분'] = df_bus_card_kor['승객연령']
df_bus_card['환승여부'] = df_bus_card_kor['환승여부']
df_bus_card['추가운임여부'] = df_bus_card_kor['추가운임여부']
df_bus_card['승차정류장'] = df_bus_card_kor['승차정류장']
df_bus_card['하차정류장'] = df_bus_card_kor['하차정류장']

df_bus_card['승차시각']

0      2020-03-27 05:14:12
1      2020-03-27 05:15:14
2      2020-03-27 05:23:43
3      2020-03-27 05:24:49
4      2020-03-27 05:28:48
               ...
4978   2020-03-27 23:25:13
4979   2020-03-27 23:27:40
4980   2020-03-27 23:28:29
4981   2020-03-27 23:33:28
4982   2020-03-27 23:36:22
Name: 승차시각, Length: 4983, dtype: datetime64[ns]

#### - 버스내체류시간 = 하차시각(분) - 승차시각(분)

In [43]:
df_bus_card['버스내체류시간(분)'] = pd.to_datetime(df_bus_card['하차시각']).dt.minute - \
                                    pd.to_datetime(df_bus_card['승차시각']).dt.minute

df_bus_card

,승차시각,하차시각,승객구분,환승여부,추가운임여부,승차정류장,하차정류장,버스내체류시간(분)
0,2020-03-27 05:14:12,2020-03-27 05:17:14,일반,N,N,문덕사거리,성우오토모티브,3
1,2020-03-27 05:15:14,2020-03-27 05:49:56,일반,N,N,준양주택3차,오거리,34
2,2020-03-27 05:23:43,2020-03-27 05:46:59,일반,N,N,두호동주민센터,남구보건소,23
3,2020-03-27 05:24:49,2020-03-27 05:54:12,일반,N,N,천마아파트,홈플러스,30
4,2020-03-27 05:28:48,2020-03-27 05:52:31,일반,N,N,오천농협세계지점,죽도시장,24
...,...,...,...,...,...,...,...,...
4978,2020-03-27 23:25:13,2020-03-27 23:28:00,일반,Y,N,포은중앙도서관,롯데아파트,3
4979,2020-03-27 23:27:40,2020-03-27 23:33:19,일반,N,N,KTX포항역(시내행),우현경로당,6
4980,2020-03-27 23:28:29,2020-03-27 23:34:46,일반,N,N,시외버스터미널,연일파출소,6
4981,2020-03-27 23:33:28,2020-03-27 23:34:42,일반,N,N,우현경로당,도심환승센터,1
4982,2020-03-27 23:36:22,2020-03-27 23:40:14,일반,N,N,포은중앙도서관,두호남부초등학교,4

#### - 이상치가 있는 것을 확인

In [44]:
df_bus_card.describe()

        버스내체류시간(분)
count  4983.000000
mean      0.147702
std      24.124315
min     -59.000000
25%      -5.000000
50%       8.000000
75%      15.000000
max      52.000000

In [45]:
df_bus_card[df_bus_card['버스내체류시간(분)'] < 0]

,승차시각,하차시각,승객구분,환승여부,추가운임여부,승차정류장,하차정류장,버스내체류시간(분)
18,2020-03-27 05:40:19,2020-03-27 06:26:08,일반,N,N,청하환승센터,교보생명,-14
24,2020-03-27 05:46:10,2020-03-27 06:07:06,일반,N,N,포항테크노파크,죽도시장,-39
28,2020-03-27 05:48:50,2020-03-27 06:04:20,일반,N,N,동부초등학교,현대제철,-44
30,2020-03-27 05:51:09,2020-03-27 06:05:13,일반,N,N,연일전통시장,홈플러스,-46
31,2020-03-27 05:51:16,2020-03-27 06:00:00,일반,N,N,대송교회,단지주유소,-51
...,...,...,...,...,...,...,...,...
4952,2020-03-27 22:55:17,2020-03-27 23:01:27,일반,N,N,죽도시장,교보생명,-54
4953,2020-03-27 22:55:50,2020-03-27 23:08:54,일반,N,N,시외버스터미널,창포사거리,-47
4954,2020-03-27 22:57:25,2020-03-27 23:02:11,일반,N,N,럭키아파트,장성초등학교,-55
4955,2020-03-27 22:57:58,2020-03-27 23:02:59,일반,N,N,장성럭키2차,두호초등학교,-55
4956,2020-03-27 22:59:05,2020-03-27 23:17:10,일반,N,N,시외버스터미널,안강우체국,-42

####  - 이상치 제거: 음수에 -1을 곱함

In [46]:
df_bus_card.loc[df_bus_card['버스내체류시간(분)'] < 0, '버스내체류시간(분)'] = 60 - (df_bus_card['버스내체류시간(분)'] * (-1))

df_bus_card.describe()

        버스내체류시간(분)
count  4983.000000
mean     15.283163
std      10.387528
min       0.000000
25%       7.000000
50%      13.000000
75%      21.000000
max      59.000000

In [48]:
df_bus_card['기준년도'] = df_bus_card['승차시각'].dt.year
df_bus_card['기준월'] = df_bus_card['승차시각'].dt.month
df_bus_card['기준일'] = df_bus_card['승차시각'].dt.day
df_bus_card['기준시각'] = df_bus_card['승차시각'].dt.hour
df_bus_card['기준시각(분)'] = df_bus_card['승차시각'].dt.minute

df_bus_card

,승차시각,하차시각,승객구분,환승여부,추가운임여부,승차정류장,하차정류장,버스내체류시간(분),기준년도,기준월,기준일,기준시각,기준시각(분)
0,2020-03-27 05:14:12,2020-03-27 05:17:14,일반,N,N,문덕사거리,성우오토모티브,3,2020,3,27,5,14
1,2020-03-27 05:15:14,2020-03-27 05:49:56,일반,N,N,준양주택3차,오거리,34,2020,3,27,5,15
2,2020-03-27 05:23:43,2020-03-27 05:46:59,일반,N,N,두호동주민센터,남구보건소,23,2020,3,27,5,23
3,2020-03-27 05:24:49,2020-03-27 05:54:12,일반,N,N,천마아파트,홈플러스,30,2020,3,27,5,24
4,2020-03-27 05:28:48,2020-03-27 05:52:31,일반,N,N,오천농협세계지점,죽도시장,24,2020,3,27,5,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4978,2020-03-27 23:25:13,2020-03-27 23:28:00,일반,Y,N,포은중앙도서관,롯데아파트,3,2020,3,27,23,25
4979,2020-03-27 23:27:40,2020-03-27 23:33:19,일반,N,N,KTX포항역(시내행),우현경로당,6,2020,3,27,23,27
4980,2020-03-27 23:28:29,2020-03-27 23:34:46,일반,N,N,시외버스터미널,연일파출소,6,2020,3,27,23,28
4981,2020-03-27 23:33:28,2020-03-27 23:34:42,일반,N,N,우현경로당,도심환승센터,1,2020,3,27,23,33
4982,2020-03-27 23:36:22,2020-03-27 23:40:14,일반,N,N,포은중앙도서관,두호남부초등학교,4,2020,3,27,23,36

#### - 모든 데이터셋 통합하기

In [50]:
from datetime import datetime

In [64]:
start_date = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

df_bus_card_tot = pd.DataFrame()

for i in range(0, 100, 1) :
    
    # 1. csv, excel 파일 불러오기
    
    file_path1 = 'C:/users/thdwo/busan_jupyter/04_교통데이터분석/01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard ({})/trfcard.csv'.format(i)
    file_path2 = 'C:/users/thdwo/busan_jupyter/04_교통데이터분석/01_data_원본/포항시_버스_사용자_교통카드_사용_내역/trfcard ({})/trfcard_columns.xlsx'.format(i)

    df_bus_card_org = pd.read_csv(file_path1)
    df_bus_card_col_org = pd.read_excel(file_path2, header = 2, usecols = 'B:C')
    
    # 2. 컬럼명 한글로 바꾸기
    
    df_bus_card_col_dict = df_bus_card_col_org.to_dict('records')
    
    df_bus_card_col_new_dict = {}
    
    for i in range(0, len(df_bus_card_col_dict), 1) :
        df_bus_card_col_new_dict[df_bus_card_col_dict[i]['컬럼명 (영문)']] = \
        df_bus_card_col_dict[i]['컬럼명 (한글)']
        
    df_bus_card_kor = df_bus_card_org.rename(columns = df_bus_card_col_new_dict)
    
    # 3. 분석요소 추출 및 추가하기
    
    df_bus_card_kor = df_bus_card_kor.astype({'승차시각' : 'str'})
    df_bus_card_kor = df_bus_card_kor.astype({'하차시각' : 'str'})
    
    df_bus_card = pd.DataFrame()
    
    df_bus_card['승차시각'] = pd.to_datetime(df_bus_card_kor['승차시각'])
    df_bus_card['하차시각'] = pd.to_datetime(df_bus_card_kor['하차시각'])
    df_bus_card['승객구분'] = df_bus_card_kor['승객연령']
    df_bus_card['환승여부'] = df_bus_card_kor['환승여부']
    df_bus_card['추가운임여부'] = df_bus_card_kor['추가운임여부']
    df_bus_card['승차정류장'] = df_bus_card_kor['승차정류장']
    df_bus_card['하차정류장'] = df_bus_card_kor['하차정류장']

    df_bus_card['버스내체류시간(분)'] = df_bus_card['하차시각'].dt.minute - df_bus_card['승차시각'].dt.minute
    
    df_bus_card.loc[(df_bus_card['버스내체류시간(분)'] < 0), '버스내체류시간(분)'] = 60 - (df_bus_card['버스내체류시간(분)'] * -1)
    
    df_bus_card['기준년도'] = df_bus_card['승차시각'].dt.year
    df_bus_card['기준월'] = df_bus_card['승차시각'].dt.month
    df_bus_card['기준일'] = df_bus_card['승차시각'].dt.day
    df_bus_card['기준시간'] = df_bus_card['승차시각'].dt.hour
    df_bus_card['기준시간(분)'] = df_bus_card['승차시각'].dt.minute
    
    # 4. 데이터 추가(통합하기)
    
    df_bus_card_tot = df_bus_card_tot.append(df_bus_card, ignore_index = True )
    
end_date = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

print('전체 실행 시간 : ', start_date, ' - ', end_date)
print('전체 데이터셋 개수 : ', len(df_bus_card_tot))
df_bus_card_tot.head()

전체 실행 시간 :  2022-03-07 14:14:37  -  2022-03-07 14:16:34
전체 데이터셋 개수 :  1057872

,승차시각,하차시각,승객구분,환승여부,추가운임여부,승차정류장,하차정류장,버스내체류시간(분),기준년도,기준월,기준일,기준시간,기준시간(분)
0,2020-03-27 05:14:12,2020-03-27 05:17:14,일반,N,N,문덕사거리,성우오토모티브,3,2020,3,27,5,14
1,2020-03-27 05:15:14,2020-03-27 05:49:56,일반,N,N,준양주택3차,오거리,34,2020,3,27,5,15
2,2020-03-27 05:23:43,2020-03-27 05:46:59,일반,N,N,두호동주민센터,남구보건소,23,2020,3,27,5,23
3,2020-03-27 05:24:49,2020-03-27 05:54:12,일반,N,N,천마아파트,홈플러스,30,2020,3,27,5,24
4,2020-03-27 05:28:48,2020-03-27 05:52:31,일반,N,N,오천농협세계지점,죽도시장,24,2020,3,27,5,28

In [67]:
df_bus_card_tot.to_csv('C:/Users/thdwo/busan_jupyter/04_교통데이터분석/02_data_통합본/df_bus_card_tot.csv', index = None)

## 2.2 기준월 및 시간대별 버스 이용량 분석 비교

## 2.3 기준시간 및 시간(분)별 버스 이용량 분석 비교

## 2.4 버스 내 체류시간

## 2.5 승차정류장 별 버스 내 체류시간