## 단계구분도 그리기

In [1]:
# pandas, matplotlib, json, folium 라이브러리 호출

import pandas as pd
import matplotlib.pyplot as plt
import json
import folium
plt.rc('font', family = 'Malgun Gothic')

In [2]:
# 'df_대기오염물질 배출량.csv' 파일 불러오기

df = pd.read_csv('./데이터 통합용/df_대기오염물질 배출량.csv')
df = df.set_index('지역')
df

,일산화탄소(CO),질산화물(NOx),황산화물(SOx),총먼지(TSP),미세먼지(PM10),미세먼지(PM2.5),Black Carbon(BC),휘발성유기화합물(VOC),암모니아(NH)
지역,,,,,,,,,
강원도,50995652,79834417,13802481,36165196,9771796,4109457,748947,30262580,14848233
경기도,136960058,178980916,8859353,84050233,31342317,10487681,3109508,190939659,47387368
경상남도,49198641,73050059,22596196,45799289,11984146,4726004,1031456,89168391,26920346
경상북도,96585111,104097649,37717738,107358028,45299533,22006791,2055265,89303873,36543850
광주광역시,7955525,12270179,172932,5225274,1710002,546285,153216,15721745,967862
대구광역시,17213386,26369636,2595203,10707805,3911124,1293610,338163,31875289,1668164
대전광역시,10659806,16050799,492180,5270663,1908298,653448,219448,16758270,764088
부산광역시,26661660,49950866,7897187,17031459,6885594,2644114,525045,42340472,1619633
서울특별시,59091323,88318614,1095384,31068615,15129997,3973381,1498115,72392596,3469369
세종특별자치시,4956050,5260258,79732,2500427,1024217,345444,122819,5961807,2759517
울산광역시,31399616,48718539,42794244,8932378,4079779,2274013,298484,91961349,15129468
인천광역시,42473267,54996410,12165228,22496356,7601495,2701129,607477,55060920,7166199
전라남도,64643232,105268745,58621175,71464132,28206197,13155832,1129608,88957759,43726932
전라북도,46256989,38561770,3760826,42097476,10629234,3562598,773400,69845741,35196862
제주특별자치도,11130074,17284695,1835756,10027606,3495486,1065148,223209,8999552,7655447
충청남도,65226479,107613430,69989410,81840902,37203474,18129171,1317944,78132426,53162788
충청북도,42066531,60898861,7222625,32096166,9461854,3591283,852934,43144277,16981034

In [3]:
# df의 3 ,4 ,5 열의 모든 행 df로 불러오기

df = df.iloc[:, 3:6]
df.dtypes
df

          총먼지(TSP)  미세먼지(PM10)  미세먼지(PM2.5)
지역
강원도       36165196     9771796      4109457
경기도       84050233    31342317     10487681
경상남도      45799289    11984146      4726004
경상북도     107358028    45299533     22006791
광주광역시      5225274     1710002       546285
대구광역시     10707805     3911124      1293610
대전광역시      5270663     1908298       653448
부산광역시     17031459     6885594      2644114
서울특별시     31068615    15129997      3973381
세종특별자치시    2500427     1024217       345444
울산광역시      8932378     4079779      2274013
인천광역시     22496356     7601495      2701129
전라남도      71464132    28206197     13155832
전라북도      42097476    10629234      3562598
제주특별자치도   10027606     3495486      1065148
충청남도      81840902    37203474     18129171
충청북도      32096166     9461854      3591283

#### - 모든 시도의 각 행을 행정구역 수로 나눈 몫만 넣기
#### 강원도

In [5]:
df.iloc[0, 0] = df.iloc[0, 0] // 7
df.iloc[0, 1] = df.iloc[0, 1] // 7
df.iloc[0, 2] = df.iloc[0, 2] // 7

C:\Users\thdwo\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\thdwo\anaconda3\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

#### 경기도

In [6]:
df.iloc[1, 0] = df.iloc[1, 0] // 28
df.iloc[1, 1] = df.iloc[1, 1] // 28
df.iloc[1, 2] = df.iloc[1, 2] // 28

#### 경상남도

In [7]:
df.iloc[2, 0] = df.iloc[2, 0] // 8
df.iloc[2, 1] = df.iloc[2, 1] // 8
df.iloc[2, 2] = df.iloc[2, 2] // 8

#### 경상북도

In [8]:
df.iloc[3, 0] = df.iloc[3, 0] // 10
df.iloc[3, 1] = df.iloc[3, 1] // 10
df.iloc[3, 2] = df.iloc[3, 2] // 10

#### 전라남도

In [9]:
df.iloc[12, 0] = df.iloc[12, 0] // 5
df.iloc[12, 1] = df.iloc[12, 1] // 5
df.iloc[12, 2] = df.iloc[12, 2] // 5

#### 전라북도

In [10]:
df.iloc[13, 0] = df.iloc[13, 0] // 6
df.iloc[13, 1] = df.iloc[13, 1] // 6
df.iloc[13, 2] = df.iloc[13, 2] // 6

#### 충청남도

In [11]:
df.iloc[15, 0] = df.iloc[15, 0] // 8
df.iloc[15, 1] = df.iloc[15, 1] // 8
df.iloc[15, 2] = df.iloc[15, 2] // 8

#### 충청북도

In [12]:
df.iloc[16, 0] = df.iloc[16, 0] // 3
df.iloc[16, 1] = df.iloc[16, 1] // 3
df.iloc[16, 2] = df.iloc[16, 2] // 3

#### 제주도

In [13]:
df.iloc[14, 0] = df.iloc[14, 0] // 2
df.iloc[14, 1] = df.iloc[14, 1] // 2
df.iloc[14, 2] = df.iloc[14, 2] // 2

In [14]:
df

         총먼지(TSP)  미세먼지(PM10)  미세먼지(PM2.5)
지역
강원도       5166456     1395970       587065
경기도       3001794     1119368       374560
경상남도      5724911     1498018       590750
경상북도     10735802     4529953      2200679
광주광역시     5225274     1710002       546285
대구광역시    10707805     3911124      1293610
대전광역시     5270663     1908298       653448
부산광역시    17031459     6885594      2644114
서울특별시    31068615    15129997      3973381
세종특별자치시   2500427     1024217       345444
울산광역시     8932378     4079779      2274013
인천광역시    22496356     7601495      2701129
전라남도     14292826     5641239      2631166
전라북도      7016246     1771539       593766
제주특별자치도   5013803     1747743       532574
충청남도     10230112     4650434      2266146
충청북도     10698722     3153951      1197094

#### - 시도의 경계가 나타나있는 json 파일을 불러오기
#### - 단, utf-8로 불러오는 것이 필수

In [15]:
geo_path = './korea.json'
geo_str = json.load(open(geo_path, encoding = 'utf-8'))

#### - dust라는 리스트를 만들어 각 열의 이름을 넣음
#### - for 구문을 사용하여 dust에서 이름을 하나씩 빼낸 뒤
#### - df[i]에 하나씩 넣어 데이터 호출
#### - columns에는 지역이름값, df[i]값
#### - key_on에는 json파일의 feature.properties.CTP_KOR_NM 값을 넣음
#### - 단, 이 값은 위의 df.index값과 정확히 일치해야 함
#### - display(m) = plt.show() 와 같은 역할

In [1]:
dust = ['총먼지(TSP)', '미세먼지(PM10)', '미세먼지(PM2.5)']

for i in dust:
    
    map = folium.Map(location = [36.8, 127.5], zoom_start = 7, width = 800, length = 300)
    
    map.choropleth(geo_data = geo_str,
                      data = df[i],
                      columns = [df.index, df[i]],
                      fill_color = 'Reds',
                      key_on = 'feature.properties.CTP_KOR_NM')
    display(map)

NameError: name 'folium' is not defined